name: Build Docker Image

on:
  push:
    branches: [ main, master ]
    tags: [ "v*" ]
    paths:
      - Dockerfile
      - pgb.go
      - go.mod
      - go.sum
      - .github/workflows/docker.yml
  pull_request:
    branches: [ main, master ]
    paths:
      - Dockerfile
      - pgb.go
      - go.mod
      - go.sum
      - .github/workflows/docker.yml

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repo name
        id: prep
        run: echo "repo_lc=${REPO,,}" >> $GITHUB_OUTPUT
        env:
          REPO: ${{ github.repository }}

      - name: Sanitize ref name
        id: ref
        run: echo "ref_name_safe=$(echo '${{ github.ref_name }}' | tr '/' '-')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: |
            ghcr.io/${{ steps.prep.outputs.repo_lc }}:latest
            ghcr.io/${{ steps.prep.outputs.repo_lc }}:${{ github.sha }}
            ${{ (startsWith(github.ref, 'refs/tags/')) && format('ghcr.io/{0}:{1}', steps.prep.outputs.repo_lc, steps.ref.outputs.ref_name_safe) || '' }}
